/* Ví Rõ 2 — device-local ledger. All totals are stored as integer VND. */
(() => {
  'use strict';
  const C=window.ViRo,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const num=n=>new Intl.NumberFormat('vi-VN').format(n),vnd=n=>num(n)+' ₫',usd=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
  const day=s=>s.split('-').reverse().join('/');
  const titles={overview:'Tổng quan',transactions:'Giao dịch',funds:'Quỹ của tôi',planning:'Kế hoạch',backup:'Dữ liệu & sao lưu'};
  const kinds={spend:'Chi tiêu',save:'Tiết kiệm',borrow:'Tiền vay'};
  const incomeCategories=['Lương','Thưởng','Kinh doanh','Làm thêm','Được tặng','Hoàn tiền','Khác'];
  const categories=['Ăn uống','Đi lại','Nhà ở','Mua sắm','Sức khỏe','Học tập','Công việc','Giải trí','Gia đình','Khác'];
  const uid=prefix=>prefix+'_'+(crypto.randomUUID?crypto.randomUUID():Date.now()+'_'+Math.random().toString(36).slice(2));
  let deviceStorage;
  try{deviceStorage=window.localStorage;}catch{deviceStorage={getItem(){throw new Error('Trình duyệt đang chặn lưu trữ dữ liệu.');},setItem(){throw new Error('Không có quyền lưu dữ liệu.');}};}
  const storage=new window.ViRoStore(deviceStorage,location.pathname,navigator.locks);
  let state=storage.load(),page='overview',month=C.today().slice(0,7),pageIndex=0,filter={q:'',type:'',fund:''},showArchived=false,cache=null,opener=null,timer;
  const modal=$('#modal');
  const fmt=n=>state.settings.display==='USD'&&state.settings.fxRate?'≈ '+usd(n/state.settings.fxRate):vnd(n);
  const secondary=n=>state.settings.display==='USD'?`<small class="money-secondary">${vnd(n)}</small>`:'';
  const money=n=>`<span>${fmt(n)}</span>${secondary(n)}`;
  const balance=()=>cache||(cache=C.ledger(state));
  const name=id=>C.getFund(state,id).name;
  const opts=(list,value)=>list.map(([v,l])=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(l)}</option>`).join('');
  const field=(label,key,value=0,hint='')=>`<label class="field">${esc(label)}<input name="${key}" inputmode="numeric" value="${num(value)}" required autocomplete="off"><span class="hint">${hint}</span></label>`;
  function moneyHints(root=document){
    root.querySelectorAll('input[inputmode="numeric"],input[inputmode="decimal"]').forEach(input=>{
      let hint=input.nextElementSibling;
      if(!hint?.classList.contains('money-hint')){hint=document.createElement('span');hint.className='money-hint';hint.id=uid('amount_hint');hint.setAttribute('aria-live','polite');input.insertAdjacentElement('afterend',hint);input.setAttribute('aria-describedby',hint.id);}
      const curr=['amount','interest'].includes(input.name)?input.form?.elements.currency?.value||'VND':'VND';
      try{hint.textContent=input.value.trim()?(curr==='USD'?new Intl.NumberFormat('vi-VN',{minimumFractionDigits:2,maximumFractionDigits:2}).format(C.usdInput(input.value)/100)+' USD':vnd(C.moneyInput(input.value))):(curr==='USD'?'Ví dụ: 100,50 USD':'Ví dụ: 1.000.000 ₫');hint.classList.remove('invalid');}
      catch{hint.textContent=curr==='USD'?'Nhập số USD, tối đa 2 chữ số thập phân.':'Nhập số tiền VNĐ hợp lệ.';hint.classList.add('invalid');}
    });
  }
  document.addEventListener('input',e=>{if(e.target.matches('input[inputmode]'))moneyHints(e.target.form||document);});
  const formEnd=(text='Lưu')=>`<p class="form-error" role="alert"></p><div class="form-actions"><button type="button" data-close>Hủy</button><button type="submit" class="primary">${text}</button></div>`;
  function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('#toast').classList.remove('show'),4500);}
  function error(form,e){form.querySelector('.form-error').textContent=e.message||String(e);}
  async function commit(n,recovery=false){state=await storage.save(n,recovery);cache=null;render();}
  function showModal(title,subtitle,html){if(!modal.open)opener=document.activeElement;$('#modal-content').innerHTML=`<div class="modal-inner"><div class="modal-head"><div><h2 id="modal-title">${esc(title)}</h2><p>${esc(subtitle)}</p></div><button class="close" aria-label="Đóng">×</button></div>${html}</div>`;$('.close').onclick=()=>modal.close();$$('[data-close]').forEach(b=>b.onclick=()=>modal.close());moneyHints(modal);if(!modal.open)modal.showModal();}
  modal.addEventListener('close',()=>{if(opener?.isConnected)opener.focus();else $('#add-button').focus();});
  function submit(form,action,close=true){form.onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await action(new FormData(form));if(close)modal.close();}catch(err){error(form,err);}finally{b.disabled=false;}};}
  function confirm(title,body,action,label='Xác nhận'){showModal(title,'Kiểm tra trước khi tiếp tục.',`<form id="confirm-form">${body}${formEnd(label)}</form>`);submit($('#confirm-form'),action);}
  function download(content,file,type='application/json'){const u=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=u;a.download=file;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),5000);}
  function exportJSON(){if(storage.problem){toast('Dữ liệu cần phục hồi. Hãy tải dữ liệu gốc trong mục sao lưu.');return;}download(C.backup(state),`ViRo-backup-${C.today()}-${Date.now()}.json`);try{localStorage.setItem(storage.exportKey,new Date().toISOString());}catch{}toast('Đã tạo bản sao lưu. Hãy kiểm tra thư mục Tải xuống.');render();}
  function setup(){
    const total=state.funds.reduce((sum,f)=>sum+f.opening,0),parts=state.funds.filter(f=>!f.archived&&f.id!=='spend');
    showModal(state.initialized?'Sửa số tiền ban đầu':'Bắt đầu với tiền hiện có','Nhập số tiền tại thời điểm bắt đầu dùng sổ. Đơn vị: VNĐ.',`<form id="setup-form"><div class="form-grid">${field('Tổng tiền hiện có','total',total,'Cộng tiền mặt và tài khoản, gồm cả tiết kiệm và tiền vay còn giữ. Không cộng khoản nợ vào đây.')}${field('Nợ phải trả','debt',state.openingDebt,'Số tiền gốc bạn còn nợ. Không có nợ thì để 0.')}</div><details class="setup-details" ${parts.some(f=>f.opening)?'open':''}><summary>Chia tiền tiết kiệm / tiền vay / quỹ riêng <span>Không bắt buộc</span></summary><p class="fine muted">Các khoản dưới đây đã nằm trong tổng tiền ở trên. Phần còn lại tự vào quỹ ${esc(name('spend'))}.</p><div class="form-grid">${parts.map(f=>field(f.kind==='borrow'?'Tiền vay còn giữ (chưa tiêu)':f.name,'split_'+f.id,f.opening,f.kind==='borrow'?'Chỉ tách phần còn trong ví / tài khoản để cảnh báo khi dùng.':f.kind==='save'?'Để dành; app cảnh báo khi rút chi.':'Số tiền dành riêng cho quỹ này.')).join('')}</div></details><p class="setup-result inline-info" id="setup-result" aria-live="polite"></p><p class="fine muted">Nợ được theo dõi riêng. Nhập nợ không tự cộng hay trừ tiền đang có. ${state.transactions.length?'Sửa số ban đầu sẽ tính lại toàn bộ lịch sử.':'Sau bước này: nhận thêm tiền thì dùng Thêm tiền, mua sắm thì dùng Chi tiêu.'}</p>${formEnd('Lưu và bắt đầu')}</form>`);
    const form=$('#setup-form');
    function readOpening(){const f=new FormData(form),n=C.copy(state),total=C.moneyInput(f.get('total'));n.openingDebt=C.moneyInput(f.get('debt'));for(const part of parts)n.funds.find(x=>x.id===part.id).opening=C.moneyInput(f.get('split_'+part.id));const allocated=n.funds.filter(x=>x.id!=='spend').reduce((sum,x)=>sum+x.opening,0);if(allocated>total)throw new Error('Các khoản chia riêng vượt tổng tiền '+vnd(allocated-total)+'. Hãy giảm khoản chia hoặc sửa tổng tiền.');if(n.funds.find(x=>x.id==='borrow').opening>n.openingDebt)throw new Error('Tiền vay còn giữ không thể lớn hơn nợ phải trả. Kiểm tra lại hai số này.');n.funds.find(x=>x.id==='spend').opening=total-allocated;n.initialized=true;return n;}
    function preview(){try{const n=readOpening();$('#setup-result').textContent='Tiền dùng hằng ngày: '+vnd(n.funds.find(x=>x.id==='spend').opening)+'. Tổng tiền vẫn là '+vnd(n.funds.reduce((sum,x)=>sum+x.opening,0))+'.';$('#setup-result').classList.remove('expense');}catch(e){$('#setup-result').textContent=e.message;$('#setup-result').classList.add('expense');}}
    form.addEventListener('input',preview);preview();
    submit(form,async()=>{await commit(readOpening());toast('Đã lưu số tiền ban đầu.');});
  }
  function exchange(wantUSD=false){
    showModal('Tỷ giá & đơn vị hiển thị','Sổ tiền luôn ghi bằng VNĐ; USD là giá trị quy đổi.',`<form id="rate-form">${field('1 USD bằng bao nhiêu VNĐ?','rate',state.settings.fxRate,'Dùng tỷ giá thực tế của ngân hàng / giao dịch bạn chọn. App không lấy tỷ giá thị trường tự động.')}<label class="field spaced">Xem số dư bằng<select name="display">${opts([['VND','VND · số tiền trong sổ'],['USD','USD · giá trị quy đổi tham khảo']],wantUSD?'USD':state.settings.display)}</select></label><p class="inline-info">Đổi tỷ giá hiển thị không sửa giao dịch cũ. Mỗi giao dịch USD giữ riêng số đô và tỷ giá tại lúc ghi nhận.</p>${formEnd('Lưu tỷ giá')}</form>`);
    submit($('#rate-form'),async f=>{const n=C.copy(state);n.settings.fxRate=C.rate(C.moneyInput(f.get('rate')));n.settings.display=f.get('display');await commit(n);toast('Đã cập nhật tỷ giá hiển thị.');});
  }
  function editFund(fundId=null){
    const f=fundId?C.getFund(state,fundId):{id:uid('fund'),name:'',kind:'spend',opening:0,budget:0,goal:0,archived:false};
    showModal(fundId?'Chỉnh quỹ':'Tạo quỹ riêng','Mỗi đồng chỉ nằm trong một quỹ tại một thời điểm.',`<form id="fund-form"><div class="form-grid"><label class="field full">Tên quỹ<input name="name" value="${esc(f.name)}" placeholder="Ví dụ: Ăn uống, Thiết bị, Du lịch…" maxlength="60" required autofocus></label><label class="field full">Loại quỹ<select name="kind" ${fundId?'disabled':''}>${opts((f.kind==='borrow'?[['borrow','Tiền vay']]:[['spend','Chi tiêu · dùng hằng ngày'],['save','Tiết kiệm · cảnh báo khi rút']]),f.kind)}</select><span class="hint">Loại quỹ được giữ cố định sau khi tạo.</span></label>${field('Ngân sách mỗi tháng (VNĐ)','budget',f.budget,'0 = không đặt giới hạn. Gồm chi tiêu và lãi / phí.')}${field('Mục tiêu số dư (VNĐ)','goal',f.goal,'0 = không đặt mục tiêu.')}</div>${!fundId?'<p class="inline-info">Quỹ mới bắt đầu với 0 ₫. Dùng Chuyển quỹ để phân bổ tiền đã có; chỉ dùng Thêm tiền khi thực sự nhận thêm tiền từ bên ngoài.</p>':''}${formEnd(fundId?'Lưu thay đổi':'Tạo quỹ')}</form>`);
    submit($('#fund-form'),async data=>{const n=C.saveFund(state,{...f,name:data.get('name').trim(),kind:fundId?f.kind:data.get('kind'),budget:C.moneyInput(data.get('budget')),goal:C.moneyInput(data.get('goal'))});await commit(n);toast(fundId?'Đã cập nhật quỹ.':'Đã tạo quỹ. Chuyển tiền vào để bắt đầu dùng.');});
  }
  function transactionForm(type='expense',existing=null,draft={}){
    if(!state.initialized){setup();return;}
    const b=balance(),t=existing||{},fx=t.fx;
    const categoryList=type==='income'?incomeCategories:categories;
    const selectedCategory=draft.category&&categoryList.includes(draft.category)?draft.category:t.category||categoryList[0];
    const categoryOptions=[...new Set([...categoryList,selectedCategory])];
    let currency=draft.currency||(fx?'USD':'VND');
    const candidates=state.funds.filter(f=>!f.archived&&(type==='loan'?f.kind==='borrow':type==='income'||type==='transfer'?f.kind!=='borrow':true));
    let account=draft.account||t.account||(type==='loan'?'borrow':'spend');if(!candidates.some(f=>f.id===account))account=candidates[0]?.id;
    const toFunds=state.funds.filter(f=>!f.archived&&f.kind!=='borrow'&&f.id!==account);
    const to=draft.to||t.to||toFunds[0]?.id||'';
    const amountText=draft.amountText??(fx?(fx.units/100).toFixed(2):t.amount!==undefined?num(t.amount):'');
    const interestText=draft.interestText??(fx?(fx.interestUnits/100).toFixed(2):num(t.interest||0));
    showModal(existing?'Sửa giao dịch':'Ghi giao dịch','Thêm tiền là cộng vào ví. Chi tiêu là trừ khỏi ví.',`<div class="type-tabs">${C.types.map(k=>`<button data-type="${k}" class="${k===type?'active':''}" ${existing?'disabled':''}>${C.labels[k]}</button>`).join('')}</div><form id="tx-form"><div class="amount-row"><label class="field">${type==='repay'?'Tiền trả gốc':'Số tiền'}<input class="amount-input" name="amount" inputmode="decimal" placeholder="0" value="${esc(amountText)}" required autofocus></label><label class="field">Đơn vị<select name="currency">${opts([['VND','VND'],['USD','USD']],currency)}</select></label></div><div id="fx-fields" ${currency==='VND'?'hidden':''}>${field('1 USD = … VNĐ','rate',draft.rate??fx?.rate??state.settings.fxRate,'Tỷ giá bạn chọn, được giữ nguyên trong giao dịch này.')}</div><div class="conversion-line" id="amount-preview" aria-live="polite"></div><div class="form-grid"><label class="field">Ngày<input name="date" type="date" min="1900-01-01" max="${C.today()}" value="${esc(draft.date||t.date||C.today())}" required></label><label class="field">${['income','loan'].includes(type)?'Thêm vào quỹ':'Lấy từ quỹ'}<select name="account">${opts(candidates.map(f=>[f.id,f.name]),account)}</select></label>${type==='transfer'?`<label class="field full">Quỹ nhận<select name="to">${opts(toFunds.map(f=>[f.id,f.name]),to)}</select></label>`:''}${['income','expense'].includes(type)?`<label class="field">Danh mục<select name="category">${opts(categoryOptions.map(k=>[k,k]),selectedCategory)}</select></label>`:''}${type==='repay'?`<label class="field">Lãi / phí <span id="interest-unit">(${currency})</span><input name="interest" inputmode="decimal" value="${esc(interestText)}" required><span class="hint">Có thể nhập gốc = 0 nếu chỉ trả lãi.</span></label>`:''}<label class="field ${['income','expense','repay'].includes(type)?'':'full'}">Ghi chú<input name="note" maxlength="200" value="${esc(draft.note??t.note??'')}" placeholder="Không bắt buộc"></label></div><p class="fine muted" id="account-balance"></p><div id="tx-warning"></div>${type==='transfer'?'<p class="inline-info">Chuyển quỹ chỉ đổi nơi giữ tiền, không làm tăng thu nhập hoặc chi tiêu. App không tự bù từ quỹ khác khi thiếu tiền.</p>':''}${type==='loan'?'<p class="inline-info">Nhận tiền vay tăng tiền đang giữ và dư nợ, không được tính là thu nhập.</p>':''}${type==='repay'?`<p class="inline-info">Dư nợ hiện tại: ${vnd(b.debt)}. Phần gốc làm giảm nợ; lãi / phí tính vào chi tiêu. Tiền vay dư ra khi nợ đã giảm sẽ về quỹ ${esc(name('spend'))}.</p>`:''}${formEnd(existing?'Lưu thay đổi':'Lưu giao dịch')}</form>`);
    const form=$('#tx-form');let warnSignature='';
    function read(){const f=new FormData(form),curr=f.get('currency'),r=curr==='USD'?C.rate(C.moneyInput(f.get('rate'))):0,a=C.amountInput(f.get('amount'),curr,r),interest=C.amountInput(type==='repay'?f.get('interest'):'0',curr,r);return {id:existing?.id||uid('tx'),type,date:f.get('date'),account:f.get('account'),to:type==='transfer'?f.get('to'):'',category:['income','expense'].includes(type)?f.get('category'):C.labels[type],note:f.get('note').trim(),amount:a.amount,interest:interest.amount,fx:curr==='USD'?{currency:'USD',units:a.units,interestUnits:interest.units,rate:r}:null};}
    function recalc(){
      moneyHints(form);const curr=form.elements.currency.value,a=form.elements.account.value;$('#account-balance').textContent='Quỹ '+name(a)+' hiện có '+vnd(b.funds[a])+'.';
      let warnings=[],tx;try{tx=read();$('#amount-preview').textContent=(curr==='USD'?'Quy đổi · ':'')+({income:'Cộng vào tổng tiền: +',expense:'Trừ khỏi tổng tiền: −',loan:'Tăng tiền và nợ: +',repay:'Trừ khỏi tổng tiền: −',transfer:'Chuyển giữa quỹ: '}[type])+vnd(tx.amount+tx.interest);warnings=C.warning(state,tx,existing?.id||'');}catch(e){$('#amount-preview').textContent=form.elements.amount.value?e.message:curr==='USD'?'Nhập USD như 100.50 và tỷ giá để quy đổi.':'Nhập VNĐ như 150.000.';}
      const signature=JSON.stringify([warnings,form.elements.amount.value,form.elements.interest?.value,form.elements.rate.value,form.elements.date.value,a]);
      if(signature!==warnSignature){$('#tx-warning').innerHTML=warnings.length?`<label class="check-row"><input type="checkbox" name="ack" required><span>${warnings.map(esc).join('<br>')}<br><strong>Tôi hiểu và vẫn muốn ghi nhận.</strong></span></label>`:'';warnSignature=signature;}
    }
    form.elements.currency.onchange=()=>{currency=form.elements.currency.value;$('#fx-fields').hidden=currency==='VND';form.elements.amount.value='';if(form.elements.interest)form.elements.interest.value='0';if($('#interest-unit'))$('#interest-unit').textContent='('+currency+')';recalc();form.elements.amount.focus();};
    form.elements.account.onchange=()=>{if(type==='transfer'){const choices=state.funds.filter(f=>!f.archived&&f.kind!=='borrow'&&f.id!==form.elements.account.value);form.elements.to.innerHTML=opts(choices.map(f=>[f.id,f.name]),form.elements.to.value);}recalc();};
    for(const key of ['amount','rate','date','interest'])if(form.elements[key])form.elements[key].addEventListener('input',recalc);
    $$('[data-type]').forEach(button=>button.onclick=()=>{const f=new FormData(form);transactionForm(button.dataset.type,null,{currency:f.get('currency'),amountText:f.get('amount'),interestText:f.get('interest')||'0',rate:(()=>{try{return C.moneyInput(f.get('rate'));}catch{return 0;}})(),account:f.get('account'),to:f.get('to')||'',date:f.get('date'),category:f.get('category')||categories[0],note:f.get('note')});});
    recalc();
    submit(form,async f=>{const tx=read(),warnings=C.warning(state,tx,existing?.id||'');if(warnings.length&&!f.get('ack'))throw new Error('Hãy đọc và xác nhận cảnh báo.');const n=existing?C.edit(state,tx):C.add(state,tx);if(tx.fx)n.settings.fxRate=tx.fx.rate;await commit(n);toast(existing?'Đã sửa giao dịch.':'Đã lưu giao dịch.');});
  }
  function track(value,goal){return `<div class="budget-track ${goal&&value>goal?'over':''}"><span style="width:${goal?Math.min(100,Math.round(value/goal*100)):0}%"></span></div>`;}
  function budgetBlock(value,goal){return track(value,goal)+`<div class="budget-line"><span>${goal?'Ngân sách '+fmt(goal):'Chưa đặt ngân sách'}</span><span>${goal?(value>goal?'Vượt '+fmt(value-goal):'Còn '+fmt(goal-value)):''}</span></div>`;}
  function sorted(ts){return ts.map((t,i)=>({t,i})).sort((a,b)=>b.t.date.localeCompare(a.t.date)||b.i-a.i).map(x=>x.t);}
  function filtered(){return sorted(state.transactions.filter(t=>t.date.startsWith(month)&&(!filter.type||t.type===filter.type)&&(!filter.fund||t.account===filter.fund||t.to===filter.fund)&&(!filter.q||[t.note,t.category,name(t.account),C.labels[t.type]].join(' ').toLocaleLowerCase('vi').includes(filter.q.toLocaleLowerCase('vi')))));}
  function table(ts,editable=false){return ts.length?`<div class="table-wrap"><table><thead><tr><th>Giao dịch</th><th class="amount">Số tiền</th><th>Quỹ</th>${editable?'<th><span class="sr-only">Thao tác</span></th>':''}</tr></thead><tbody>${ts.map(t=>`<tr><td><div class="tx-title">${esc(t.note||t.category)}</div><div class="tx-meta">${day(t.date)} · ${esc(C.labels[t.type])}</div></td><td class="amount ${t.type==='repay'?'expense':t.type}">${{income:'+',loan:'+',expense:'−',repay:'−',transfer:'⇄ '}[t.type]}${fmt(t.amount+t.interest)}${secondary(t.amount+t.interest)}${t.fx?`<div class="tx-meta">Gốc ${usd((t.fx.units+t.fx.interestUnits)/100)} · tỷ giá ${num(t.fx.rate)}</div>`:''}${t.interest?`<div class="tx-meta">Lãi / phí ${vnd(t.interest)}</div>`:''}</td><td><span class="tx-meta">${esc(name(t.account))}${t.type==='transfer'?'<br>→ '+esc(name(t.to)):''}</span></td>${editable?`<td><div class="row-actions"><button class="quiet" data-edit="${t.id}">Sửa</button><button class="quiet danger" data-delete="${t.id}">Xóa</button></div></td>`:''}</tr>`).join('')}</tbody></table></div>`:'<div class="empty"><h3>Chưa có giao dịch phù hợp</h3><p>Ghi một khoản thu, chi hoặc đổi bộ lọc để xem lịch sử.</p><button data-action="add">+ Ghi giao dịch</button></div>';}
  function fundCard(f,compact=false){const b=balance().funds[f.id],s=C.stats(state,month,f.id);return `<article class="fund-card ${f.archived?'archived':''}"><div class="fund-card-head"><span class="fund-kind ${f.kind}">${esc(kinds[f.kind])}${f.archived?' · Lưu trữ':''}</span><button class="quiet" data-fund-edit="${f.id}" aria-label="Chỉnh quỹ ${esc(f.name)}">···</button></div><h3>${esc(f.name)}</h3><div class="fund-value">${money(b)}</div>${f.goal?`${track(b,f.goal)}<div class="budget-line"><span>Mục tiêu ${fmt(f.goal)}</span><span>${Math.min(100,Math.round(b/f.goal*100))}%</span></div>`:f.budget?budgetBlock(s.expense,f.budget):'<div class="fund-caption">'+(f.kind==='borrow'?'Giữ riêng để tránh tiêu nhầm':f.kind==='save'?'Cảnh báo khi sử dụng':'Sẵn sàng cho khoản chi của bạn')+'</div>'}${!compact?`<div class="fund-mini-stats"><span>Chi tháng này <strong>${fmt(s.expense)}</strong></span>${f.kind!=='borrow'?`<span>Chuyển vào <strong>${fmt(s.transferIn)}</strong></span>`:''}</div><div class="fund-actions">${!f.archived?`<button data-fund-tx="${f.id}" data-kind="expense">Chi tiền</button>${f.kind!=='borrow'?`<button data-fund-tx="${f.id}" data-kind="transfer">Chuyển</button>`:''}`:''}<button class="quiet" data-history="${f.id}">Lịch sử</button>${!['spend','save','borrow'].includes(f.id)?`<button class="quiet" data-archive="${f.id}">${f.archived?'Khôi phục':'Lưu trữ'}</button>`:''}</div>`:''}</article>`;}
  function overview(){const b=balance(),s=C.stats(state,month),cats=Object.entries(s.categories).sort((a,b)=>b[1]-a[1]),recent=sorted(state.transactions.filter(t=>t.date.startsWith(month))).slice(0,5);return `<div class="balance-summary simple-balance"><div class="main-balance"><span class="label">Tổng tiền hiện có</span><div class="total-value">${money(b.total)}</div><span class="fine muted">Tiền trong tất cả quỹ, gồm tiết kiệm và tiền vay còn giữ.</span><div class="quick-money"><button class="income-button" data-action="income">+ Thêm tiền</button><button class="expense-button" data-action="expense">− Chi tiêu</button></div></div><div class="debt-summary"><span class="label">Nợ phải trả</span><strong class="debt-value expense">${money(b.debt)}</strong><span class="fine muted">Theo dõi riêng, chưa trừ khỏi tổng tiền.</span><div class="button-wrap"><button class="quiet" data-action="repay">Trả nợ</button><button class="quiet" data-action="loan">Nhận tiền vay</button></div></div></div><div class="overview-grid"><article class="panel"><div class="panel-heading"><h2>Thu chi trong tháng</h2><span class="pill">${month.split('-').reverse().join('/')}</span></div><div class="cashflow"><div><span class="label">+ Thu nhập</span><div class="value income">${money(s.income)}</div></div><div><span class="label">− Chi tiêu & lãi</span><div class="value expense">${money(s.expense)}</div></div></div>${state.settings.budget?budgetBlock(s.expense,state.settings.budget):''}<p class="fine muted">Thu nhập cộng tiền · Chi tiêu trừ tiền.</p>${s.loan||s.principal?`<div class="cashflow-foot"><span>Nhận vay ${fmt(s.loan)}</span><span>Trả gốc ${fmt(s.principal)}</span></div>`:''}</article><article class="panel"><div class="panel-heading"><h2>Tiền đang để ở đâu?</h2><button class="quiet" data-action="funds">Xem quỹ</button></div><div class="allocation">${[['Dùng chi tiêu',b.spend],['Để tiết kiệm',b.save],['Tiền vay còn giữ',b.borrow]].map(([l,v])=>`<div><span>${l}</span><strong>${fmt(v)}</strong></div>`).join('')}</div><p class="fine muted">Các khoản này đã nằm trong tổng tiền. Chuyển quỹ không làm tổng tiền thay đổi.</p></article></div><div class="lower-grid"><article class="panel"><div class="panel-heading"><h2>Giao dịch gần đây</h2><button class="quiet" data-action="transactions">Xem tất cả</button></div>${table(recent)}</article><article class="panel"><div class="panel-heading"><h2>Chi theo danh mục</h2></div>${cats.length?cats.slice(0,6).map(([k,v])=>`<div class="category-row"><div><span>${esc(k)}</span><strong>${fmt(v)}</strong></div>${track(v,s.expense)}</div>`).join(''):'<div class="empty"><p>Các danh mục sẽ xuất hiện khi bạn ghi chi tiêu.</p></div>'}</article></div><p class="fine muted spaced">Tổng tiền và nợ là số hiện tại. Thu chi và giao dịch bên dưới theo tháng bạn chọn.</p>`;}
  function transactions(){const ts=filtered(),pages=Math.max(1,Math.ceil(ts.length/30)),s=C.stats(state,month,filter.fund);pageIndex=Math.min(pageIndex,pages-1);return `<div class="totals-strip"><span>Thêm tiền<strong class="income">+${fmt(s.income)}</strong></span><span>Chi tiêu & lãi<strong class="expense">−${fmt(s.expense)}</strong></span><span>Gốc đã trả<strong>${fmt(s.principal)}</strong></span><span>Nhận vay<strong class="loan">${fmt(s.loan)}</strong></span></div><div class="panel"><div class="filters"><input id="search" type="search" placeholder="Tìm ghi chú, danh mục, quỹ…" value="${esc(filter.q)}" aria-label="Tìm giao dịch"><select id="type-filter" aria-label="Loại giao dịch">${opts([['','Mọi giao dịch'],...C.types.map(k=>[k,C.labels[k]])],filter.type)}</select><select id="fund-filter" aria-label="Quỹ tiền">${opts([['','Mọi quỹ'],...state.funds.map(f=>[f.id,f.name+(f.archived?' (lưu trữ)':'')])],filter.fund)}</select><button id="csv-button">Xuất CSV</button></div><p class="fine muted">${ts.length} giao dịch · Thống kê trên tính cả tháng${filter.fund?' của quỹ '+esc(name(filter.fund)):''}, không theo từ khóa / loại.</p>${table(ts.slice(pageIndex*30,pageIndex*30+30),true)}<div class="pagination"><span>Trang ${pageIndex+1} / ${pages}</span><div><button id="prev-page" ${pageIndex===0?'disabled':''}>Trước</button> <button id="next-page" ${pageIndex>=pages-1?'disabled':''}>Sau</button></div></div></div>`;}
  function funds(){return `<div class="section-heading"><p class="muted">Phân bổ tiền theo mục đích. Tạo quỹ không tạo thêm tiền.</p><div><button id="archive-toggle" class="quiet">${showArchived?'Ẩn quỹ lưu trữ':'Hiện quỹ lưu trữ'}</button><button class="primary" data-action="new-fund">+ Tạo quỹ</button></div></div><div class="fund-grid">${state.funds.filter(f=>showArchived||!f.archived).map(f=>fundCard(f)).join('')}</div><details class="panel wide-panel"><summary>Quỹ hoạt động như thế nào?</summary><ol class="steps"><li>Nhận tiền thực tế: dùng <strong>Thêm tiền</strong> vào đúng quỹ.</li><li>Chia tiền đã có: dùng <strong>Chuyển quỹ</strong>. Tổng tiền không đổi.</li><li>Chi từ quỹ nào thì chỉ trừ quỹ đó. Thiếu tiền: chủ động chuyển thêm, app không tự lấy từ tiết kiệm.</li><li>Tiền vay ở quỹ riêng, không chuyển thành tiền riêng. Dùng các thao tác nhận vay, chi tiêu hoặc trả nợ.</li><li>Quỹ hết tiền có thể lưu trữ; lịch sử vẫn được giữ. Khôi phục quỹ trước khi sửa giao dịch làm thay đổi số dư của quỹ đó.</li></ol></details>`;}
  function planning(){const s=C.stats(state,month),p=state.settings;return `<div class="two-col"><article class="panel"><div class="panel-heading"><h2>Ngân sách chung</h2><span class="pill">${month}</span></div><div class="big-stat">${money(s.expense)}</div>${budgetBlock(s.expense,p.budget)}<form id="budget-form" class="spaced">${field('Giới hạn mỗi tháng (VNĐ)','budget',p.budget,'0 = không đặt giới hạn. Không gồm chuyển quỹ và trả gốc.')}${formEnd('Lưu ngân sách')}</form></article><article class="panel"><div class="panel-heading"><h2>Ngày trả nợ tiếp theo</h2><span class="pill">Nhắc khi mở app</span></div><form id="due-form"><label class="field">Ngày cần trả<input name="dueDate" type="date" min="1900-01-01" max="2199-12-31" value="${esc(p.dueDate)}"></label><div class="spaced">${field('Số tiền cần chuẩn bị (VNĐ)','dueAmount',p.dueAmount,'Nhập theo lịch trả nợ của bạn, gồm cả gốc và lãi nếu có.')}</div><p class="fine muted">Để tắt nhắc: xóa ngày và nhập 0. Sau khi trả xong, tự cập nhật kỳ tiếp theo.</p>${formEnd('Lưu lịch nhắc')}</form></article></div><div class="section-heading spaced"><h2>Mục tiêu từng quỹ</h2><button data-action="new-fund">+ Tạo mục tiêu / quỹ</button></div><div class="fund-grid">${state.funds.filter(f=>!f.archived&&f.kind!=='borrow').map(f=>fundCard(f,true)).join('')}</div><p class="fine muted spaced">Chọn dấu ··· trên quỹ để đặt mục tiêu và ngân sách riêng. Các ngân sách là mức giới hạn chi tiêu, không phải khoản tiền mới được cộng vào sổ.</p>`;}
  function backups(){let last='Chưa xuất bản sao lưu';try{const d=localStorage.getItem(storage.exportKey);if(d)last='Lần tạo tệp gần nhất: '+new Date(d).toLocaleString('vi-VN');}catch{}return `<div class="backup-grid"><article class="panel backup-card"><h2>Xuất JSON</h2><p>Giữ toàn bộ quỹ, giao dịch, tỷ giá đã ghi và kế hoạch. Dùng để phục hồi hoặc chuyển thiết bị.</p><p class="fine">${esc(last)}</p><button class="primary" data-action="export">Tải bản sao lưu</button></article><article class="panel backup-card"><h2>Nhập bản sao lưu</h2><p>Đọc được JSON phiên bản 1 và 2. Kiểm tra số dư trước khi xác nhận thay thế sổ hiện tại.</p><input type="file" id="import-file" accept=".json,application/json" class="file-input" aria-label="Chọn JSON sao lưu"><p class="form-error" id="import-error" role="alert"></p></article><article class="panel backup-card"><h2>Phục hồi & cứu hộ</h2><p>Quay lại lần lưu trước hoặc tải nguyên dữ liệu gốc để kiểm tra khi có lỗi.</p><div class="button-wrap"><button id="restore-button">Phục hồi lần trước</button><button id="legacy-button">Bản trước nâng cấp</button><button id="raw-button" class="quiet">Tải dữ liệu gốc</button></div></article><article class="panel backup-card"><h2>Thiết lập sổ</h2><p>Số dư ban đầu luôn có trước toàn bộ lịch sử giao dịch. Điều chỉnh sẽ kiểm tra lại tất cả số dư.</p><div class="button-wrap"><button data-action="setup">Số dư ban đầu</button><button data-action="rate">Tỷ giá USD</button></div></article></div><article class="panel wide-panel"><h2>Quyền riêng tư & lưu trữ</h2><p class="fine muted spaced">Dữ liệu nằm trên trình duyệt này, tại địa chỉ website này. Không tự đồng bộ giữa máy. Xóa dữ liệu trình duyệt hoặc đổi địa chỉ có thể làm mất quyền truy cập sổ cũ; hãy xuất JSON định kỳ. Bản sao lưu không được mã hóa.</p><p class="fine muted">App không gửi giao dịch lên GitHub. Chỉ tải mã ứng dụng lên repository, không tải các bản sao lưu tài chính. Người dùng cùng hồ sơ trình duyệt hoặc mã cùng tên miền gốc có thể truy cập vùng lưu trữ này.</p><button class="danger" id="reset-button">Xóa sổ trên thiết bị</button></article>`;}
  function previewImport(n,title='Thay thế sổ bằng bản sao lưu?'){const b=C.ledger(n);confirm(title,`<p><strong>${n.funds.length} quỹ · ${n.transactions.length} giao dịch</strong></p><p>Tổng tiền ${vnd(b.total)}<br>Tiết kiệm ${vnd(b.save)}<br>Tiền vay ${vnd(b.borrow)}<br>Dư nợ ${vnd(b.debt)}</p><p class="inline-info">Sổ hiện tại sẽ được thay thế, không cộng gộp. Bản hiện tại hợp lệ được giữ ở Phục hồi lần trước.</p>`,async()=>{await commit(n,true);toast('Đã phục hồi dữ liệu.');},'Thay thế dữ liệu');}
  async function importFile(e){const f=e.target.files[0];if(!f)return;try{if(f.size>8000000)throw new Error('Tệp tối đa 8 MB.');previewImport(C.parseBackup(await f.text()));}catch(err){$('#import-error').textContent=err.message;}finally{e.target.value='';}}
  function exportCSV(){const cell=v=>{let s=String(v??'');if(/^[=+\-@\t\r\n]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};const rows=[['Ngày','Loại','Quỹ','Quỹ nhận','Số tiền VNĐ','Lãi phí VNĐ','USD gốc','USD lãi phí','Tỷ giá VND/USD','Danh mục','Ghi chú'],...filtered().map(t=>[t.date,C.labels[t.type],name(t.account),t.to?name(t.to):'',t.amount,t.interest,t.fx?(t.fx.units/100).toFixed(2):'',t.fx?(t.fx.interestUnits/100).toFixed(2):'',t.fx?.rate||'',t.category,t.note])];download('\uFEFF'+rows.map(r=>r.map(cell).join(',')).join('\r\n'),`ViRo-giao-dich-${month}.csv`,'text/csv;charset=utf-8');toast('Đã xuất CSV theo bộ lọc. JSON dùng để phục hồi sổ.');}
  function navigate(next){page=titles[next]?next:'overview';pageIndex=0;render();}
  function bind(){
    $$('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='add')transactionForm();else if(a==='new-fund')editFund();else if(a==='setup')setup();else if(a==='export')exportJSON();else if(a==='rate')exchange();else if(['income','expense','loan','repay'].includes(a))transactionForm(a);else navigate(a);});
    $$('[data-fund-edit]').forEach(b=>b.onclick=()=>editFund(b.dataset.fundEdit));
    $$('[data-fund-tx]').forEach(b=>b.onclick=()=>transactionForm(b.dataset.kind,null,{account:b.dataset.fundTx}));
    $$('[data-history]').forEach(b=>b.onclick=()=>{filter={q:'',type:'',fund:b.dataset.history};navigate('transactions');});
    $$('[data-archive]').forEach(b=>b.onclick=()=>{const f=C.getFund(state,b.dataset.archive);confirm(f.archived?'Khôi phục quỹ?':'Lưu trữ quỹ?',`<p>${esc(f.name)}. Lịch sử giao dịch vẫn được giữ nguyên.</p>`,async()=>{await commit(C.archive(state,f.id));toast('Đã cập nhật quỹ.');});});
    $$('[data-edit]').forEach(b=>b.onclick=()=>{const t=state.transactions.find(t=>t.id===b.dataset.edit);if(C.getFund(state,t.account).archived||t.to&&C.getFund(state,t.to).archived){toast('Khôi phục quỹ đang lưu trữ trước khi sửa giao dịch.');return;}transactionForm(t.type,t);});
    $$('[data-delete]').forEach(b=>b.onclick=()=>{const t=state.transactions.find(t=>t.id===b.dataset.delete);confirm('Xóa giao dịch?',`<p>${esc(t.note||t.category)} · ${vnd(t.amount+t.interest)}</p><p class="fine muted">Số dư được tính lại theo lịch sử. App chặn thao tác khiến một quỹ bị âm.</p>`,async()=>{await commit(C.remove(state,t.id));toast('Đã xóa giao dịch.');},'Xóa giao dịch');});
    if(page==='transactions'){
      $('#search').oninput=e=>{const pos=e.target.selectionStart;filter.q=e.target.value;pageIndex=0;render();$('#search').focus();$('#search').setSelectionRange(pos,pos);};
      $('#type-filter').onchange=e=>{filter.type=e.target.value;pageIndex=0;render();};$('#fund-filter').onchange=e=>{filter.fund=e.target.value;pageIndex=0;render();};
      $('#prev-page').onclick=()=>{pageIndex--;render();};$('#next-page').onclick=()=>{pageIndex++;render();};$('#csv-button').onclick=exportCSV;
    }
    if(page==='funds')$('#archive-toggle').onclick=()=>{showArchived=!showArchived;render();};
    if(page==='planning'){
      $('#budget-form [data-close]').hidden=true;$('#due-form [data-close]').hidden=true;
      submit($('#budget-form'),async f=>{const n=C.copy(state);n.settings.budget=C.moneyInput(f.get('budget'));await commit(n);toast('Đã lưu ngân sách.');},false);
      submit($('#due-form'),async f=>{const n=C.copy(state);n.settings.dueDate=f.get('dueDate');n.settings.dueAmount=C.moneyInput(f.get('dueAmount'));await commit(n);toast('Đã lưu lịch nhắc.');},false);
    }
    if(page==='backup'){
      $('#import-file').onchange=importFile;
      $('#restore-button').onclick=()=>{try{previewImport(storage.readPrevious(),'Phục hồi lần lưu trước?');}catch(e){toast(e.message);}};
      $('#raw-button').onclick=()=>{try{const raw=localStorage.getItem(storage.key);if(!raw)throw new Error('Chưa có dữ liệu gốc.');download(raw,`ViRo-rescue-${C.today()}.json`);}catch(e){toast(e.message);}};
      $('#legacy-button').onclick=()=>{try{const raw=localStorage.getItem(storage.legacy);if(!raw)throw new Error('Chưa có bản trước nâng cấp trên thiết bị này.');const old=window.ViRoV1.validate(JSON.parse(raw));download(window.ViRoV1.backup(old),`ViRo-backup-v1-${C.today()}.json`);toast('Đã tạo tệp dữ liệu trước nâng cấp.');}catch(e){toast(e.message);}};
      $('#reset-button').onclick=()=>confirm('Xóa toàn bộ sổ?',`<label class="check-row"><input name="ack" type="checkbox" required><span>Tôi đã giữ bản sao lưu cần thiết và muốn xóa sổ trên thiết bị này.</span></label>`,async f=>{if(!f.get('ack'))throw new Error('Hãy xác nhận trước khi xóa.');await commit(C.empty(),true);toast('Đã xóa sổ. Bản phục hồi gần nhất vẫn được giữ.');},'Xóa sổ');
    }
  }
  function render(){
    cache=null;$('#page-title').textContent=titles[page];$('#breadcrumb-view').textContent=titles[page];$('#page-eyebrow').textContent='';$('#month').value=month;$('.month-label').hidden=page==='backup';
    $$('nav [data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===page);if(b.dataset.view===page)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});
    $$('[data-display]').forEach(b=>{b.classList.toggle('active',b.dataset.display===state.settings.display);b.setAttribute('aria-pressed',String(b.dataset.display===state.settings.display));});
    $('#save-status').textContent=storage.problem?'Cần phục hồi dữ liệu':state.updatedAt?'Đã lưu '+new Date(state.updatedAt).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'}):'Tự lưu trên thiết bị';
    $('#currency-note').textContent=state.settings.display==='USD'?`USD tham khảo · 1 USD = ${num(state.settings.fxRate)} VNĐ · tỷ giá bạn chọn`:'Sổ tiền ghi nhận bằng VNĐ.';
    let notice=storage.problem?`<div class="notice error"><p>Không đọc được sổ: ${esc(storage.problem)}. Dữ liệu gốc được giữ nguyên.</p><button data-action="backup">Phục hồi</button></div>`:!state.initialized?'<div class="notice"><p><strong>Bắt đầu với tổng tiền bạn đang có.</strong> Nhập thêm nợ nếu có; có thể chia quỹ sau.</p><button class="primary" data-action="setup">Nhập số dư</button></div>':'';
    const p=state.settings;
    if(!storage.problem&&p.dueDate&&p.dueAmount&&balance().debt>0){const days=Math.ceil((new Date(p.dueDate+'T12:00:00')-new Date(C.today()+'T12:00:00'))/86400000);if(days<=7)notice+=`<div class="notice warning"><p><strong>${days<0?'Lịch nhắc đã qua '+(-days)+' ngày':days===0?'Nhắc trả nợ hôm nay':'Nhắc trả nợ sau '+days+' ngày'}</strong> · ${day(p.dueDate)} · ${fmt(p.dueAmount)}</p><button data-action="repay">Ghi trả nợ</button></div>`;}
    $('#global-notice').innerHTML=notice;
    $('#view').innerHTML=({overview,transactions,funds,planning,backup:backups})[page]();bind();moneyHints($('#view'));
  }
  function guide(){showModal('Cách sử dụng','Thu đúng quỹ, chi đúng mục đích.',`<ol class="steps"><li>Nhập <strong>Tổng tiền hiện có</strong> một lần, và <strong>Nợ phải trả</strong> nếu có. Tiết kiệm / tiền vay còn giữ là các phần trong tổng tiền, có thể tách ở mục mở rộng.</li><li><strong>Thêm tiền</strong> làm tổng tiền tăng; <strong>Chi tiêu</strong> làm tổng tiền giảm. Cả hai đều có danh mục. Nhận vay tăng cả tiền và nợ; trả nợ giảm tiền và nợ gốc.</li><li>Tạo quỹ riêng, rồi <strong>Chuyển quỹ</strong> để phân bổ tiền đã có. Chuyển không tính thu / chi.</li><li>Ghi từng giao dịch vào đúng quỹ. Tiền vay được giữ riêng và cảnh báo khi tiêu.</li><li>Nhập USD: chọn USD trong giao dịch, nhập tỷ giá thực tế. App tự đổi thành VNĐ và giữ nguyên tỷ giá đó trong lịch sử.</li><li>Nút VND / USD phía trên chỉ đổi cách xem số dư, không sửa lịch sử hoặc tạo giao dịch đổi ngoại tệ.</li><li>Xuất JSON định kỳ. Tự lưu không thay thế bản sao lưu riêng.</li></ol><p class="fine muted">App không kết nối ngân hàng, không tự cập nhật tỷ giá, không tự tính lãi. Dữ liệu không tự đồng bộ giữa thiết bị. Khi đổi đơn vị nhập trong biểu mẫu, số tiền được xóa để tránh hiểu nhầm.</p>`);}
  $('#add-button').onclick=()=>transactionForm();$('#guide-button').onclick=guide;$('#quick-backup').onclick=exportJSON;$('#rate-button').onclick=()=>exchange();
  $$('nav [data-view]').forEach(b=>b.onclick=()=>navigate(b.dataset.view));$('.brand').onclick=e=>{e.preventDefault();navigate('overview');};
  $('#month').onchange=e=>{if(/^\d{4}-(0[1-9]|1[0-2])$/.test(e.target.value)){month=e.target.value;pageIndex=0;render();}};
  $$('[data-display]').forEach(b=>b.onclick=async()=>{if(b.dataset.display==='USD'&&!state.settings.fxRate){exchange(true);return;}try{const n=C.copy(state);n.settings.display=b.dataset.display;await commit(n);}catch(e){toast(e.message);}});
  window.addEventListener('storage',e=>{if(e.key===storage.key&&e.newValue!==storage.raw){$('#save-status').textContent='Sổ đã thay đổi ở tab khác · tải lại';toast('Tải lại trang trước khi ghi tiếp để tránh mất dữ liệu.');}});
  render();
  try{if(document.modelContext?.registerTool)Promise.resolve(document.modelContext.registerTool({name:'read_viro_summary',title:'Đọc tổng quan Ví Rõ',description:'Read current fund balances and selected month totals; no modifications.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input||Array.isArray(input)||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object.');if(storage.problem)throw new Error('Dữ liệu cần phục hồi.');return {currency:'VND',balances:balance(),funds:state.funds.map(f=>({id:f.id,name:f.name,kind:f.kind,archived:f.archived})),month,monthly:C.stats(state,month)};}})).catch(()=>{});}catch{}
})();
