/* Ví Rõ: no server, no analytics, no external dependencies. */
(() => {
  'use strict';
  const C=window.ViRo, $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=n=>new Intl.NumberFormat('vi-VN').format(n)+' ₫';
  const day=s=>s.split('-').reverse().join('/');
  const KEY='viro:v1:'+location.pathname.replace(/index\.html$/,'');
  const PREV=KEY+':previous', BACKUP=KEY+':last-export';
  const titles={overview:'Tổng quan',transactions:'Giao dịch',planning:'Kế hoạch',backup:'Dữ liệu & sao lưu'};
  const categories=['Ăn uống','Đi lại','Nhà ở','Mua sắm','Sức khỏe','Học tập','Công việc','Giải trí','Gia đình','Khác'];
  let state=C.empty(), baseRaw=null, storageProblem='', page='overview', selectedMonth=C.today().slice(0,7), pageIndex=0;
  let filter={q:'',type:'',account:''}, modalReturnFocus=null, toastTimer, cache=null;
  const modal=$('#modal');
  function notify(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4200);}
  function current(){if(!cache)cache=C.ledger(state);return cache;}
  function load(){
    try{baseRaw=localStorage.getItem(KEY);if(baseRaw)state=C.validate(JSON.parse(baseRaw));}
    catch(e){storageProblem='Không đọc được dữ liệu trên trình duyệt. Hãy vào Dữ liệu & sao lưu để cứu bản gốc hoặc phục hồi. '+e.message;state=C.empty();}
  }
  async function commit(next,{recovery=false}={}){
    if(storageProblem&&!recovery)throw new Error('Dữ liệu hiện tại cần được phục hồi trước khi ghi mới.');
    C.validate(next);
    const write=()=>{
      const existing=localStorage.getItem(KEY);
      if(existing!==baseRaw)throw new Error('Dữ liệu đã thay đổi ở tab khác. Tải lại trang trước khi ghi để tránh mất giao dịch.');
      const n=JSON.parse(JSON.stringify(next));n.revision=state.revision+1;n.updatedAt=new Date().toISOString();
      const raw=JSON.stringify(n);
      // Keep the previous valid snapshot. A failed write never updates in-memory state.
      if(existing&&!storageProblem)localStorage.setItem(PREV,existing);
      try{localStorage.setItem(KEY,raw);}catch{throw new Error('Không lưu được: trình duyệt chặn lưu trữ hoặc đã hết dung lượng. Hãy xuất dữ liệu hiện tại và giải phóng dung lượng.');}
      state=n;baseRaw=raw;cache=null;storageProblem='';render();
    };
    if(navigator.locks?.request)await navigator.locks.request(KEY,write);else write();
  }
  function download(content,name,type='application/json'){
    const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),6000);
  }
  function exportJSON(mark=true){
    download(C.backup(state),`ViRo-backup-${C.today()}-${Date.now()}.json`);
    if(mark){try{localStorage.setItem(BACKUP,new Date().toISOString());}catch{}notify('Đã tạo tệp sao lưu. Hãy kiểm tra thư mục Tải xuống.');if(page==='backup')render();}
  }
  function errorIn(form,e){form.querySelector('.form-error').textContent=e.message||String(e);}
  function showModal(title,subtitle,body){
    modalReturnFocus=document.activeElement;
    $('#modal-content').innerHTML=`<div class="modal-inner"><div class="modal-head"><div><h2 id="modal-title">${esc(title)}</h2><p>${esc(subtitle)}</p></div><button class="close" aria-label="Đóng">×</button></div>${body}</div>`;
    $('.close').onclick=()=>modal.close(); if(!modal.open)modal.showModal();
  }
  modal.addEventListener('close',()=>modalReturnFocus?.focus?.());
  function confirmAction(title,body,action,label='Xác nhận'){
    showModal(title,'Kiểm tra thông tin trước khi tiếp tục.',`${body}<form id="confirm-form"><p class="form-error" role="alert"></p><div class="form-actions"><button type="button" id="cancel-confirm">Hủy</button><button class="primary" type="submit">${esc(label)}</button></div></form>`);
    $('#cancel-confirm').onclick=()=>modal.close();
    $('#confirm-form').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;try{await action();modal.close();}catch(err){errorIn(e.target,err);}finally{btn.disabled=false;}};
  }
  const options=(list,selected)=>list.map(v=>`<option value="${esc(typeof v==='string'?v:v[0])}" ${selected===(typeof v==='string'?v:v[0])?'selected':''}>${esc(typeof v==='string'?v:v[1])}</option>`).join('');
  const moneyField=(label,name,value=0,hint='',extra='')=>`<label class="field">${label}<input name="${name}" inputmode="numeric" autocomplete="off" value="${new Intl.NumberFormat('vi-VN').format(value)}" required ${extra}><span class="hint">${hint}</span></label>`;
  function setup(){
    showModal(state.initialized?'Điều chỉnh số dư ban đầu':'Bắt đầu với số tiền hiện có','Nhập số dư trước tất cả giao dịch bạn sẽ ghi vào sổ.',`<form id="setup-form"><div class="form-grid">${moneyField('Tiền riêng để chi tiêu','spend',state.opening.spend,'Không bao gồm tiền tiết kiệm hoặc tiền vay.')}${moneyField('Tiền tiết kiệm','save',state.opening.save,'Khoản bạn muốn giữ riêng.')}${moneyField('Tiền vay còn trong tay','borrow',state.opening.borrow,'Chỉ nhập phần tiền vay chưa tiêu.')}${moneyField('Tổng dư nợ gốc phải trả','debt',state.opening.debt,'Kể cả phần tiền vay đã tiêu trước đây.')}</div><p class="inline-info">Ví dụ: đã vay 20 triệu và tiêu 5 triệu trước khi dùng app → tiền vay còn lại 15 triệu, dư nợ 20 triệu. Không cộng 15 triệu này vào tiền riêng.</p><p class="form-error" role="alert"></p><div class="form-actions"><button type="button" id="cancel-setup">Để sau</button><button class="primary" type="submit">Lưu số dư</button></div></form>`);
    $('#cancel-setup').onclick=()=>modal.close();
    $('#setup-form').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{const f=new FormData(e.target),n=JSON.parse(JSON.stringify(state));for(const k of Object.keys(n.opening))n.opening[k]=C.moneyInput(f.get(k));n.initialized=true;await commit(n);modal.close();notify('Đã lưu số dư ban đầu.');}catch(err){errorIn(e.target,err);}finally{e.submitter.disabled=false;}};
  }
  function transactionForm(type='expense',existing=null,draft=null){
    if(!state.initialized){setup();return;}
    const b=current(), t=draft||existing||{amount:0,account:type==='loan'?'borrow':'spend',to:'save',interest:0,date:C.today(),category:categories[0],note:''};
    const account=type==='loan'?'borrow':(type==='income'||type==='transfer')&&t.account==='borrow'?'spend':t.account;
    showModal(existing?'Sửa giao dịch':'Thêm giao dịch','Mọi số tiền được ghi bằng đồng Việt Nam (VNĐ).',`<div class="type-tabs">${C.types.map(k=>`<button type="button" data-type="${k}" class="${type===k?'active':''}" ${existing?'disabled':''}>${C.labels[k]}</button>`).join('')}</div><form id="tx-form"><div class="form-grid"><label class="field full">${type==='repay'?'Số tiền trả gốc':'Số tiền'}<input class="amount-input" name="amount" inputmode="numeric" autocomplete="off" placeholder="0" value="${t.amount?new Intl.NumberFormat('vi-VN').format(t.amount):''}" required autofocus><span class="amount-preview" id="amount-preview">${t.amount?fmt(t.amount):'Nhập số tiền, ví dụ 150.000'}</span></label><label class="field">Ngày giao dịch<input type="date" name="date" value="${esc(t.date)}" min="1900-01-01" max="${C.today()}" required></label><label class="field">${['income','loan'].includes(type)?'Thêm vào quỹ':'Lấy tiền từ quỹ'}<select name="account">${options((type==='loan'?['borrow']:type==='income'||type==='transfer'?['spend','save']:C.accounts).map(k=>[k,C.names[k]]),account)}</select><span class="hint" id="account-balance"></span></label>${type==='transfer'?`<label class="field full">Chuyển đến<select name="to">${options([['spend',C.names.spend],['save',C.names.save]],account==='spend'?'save':'spend')}</select></label>`:''}${type==='expense'?`<label class="field full">Danh mục<select name="category">${options(categories,t.category)}</select></label>`:''}${type==='repay'?moneyField('Lãi / phí trả kèm','interest',t.interest,'Nhập 0 nếu chỉ trả gốc.'):''}<label class="field full">Ghi chú <span class="hint">Không bắt buộc · tối đa 200 ký tự</span><textarea name="note" maxlength="200" placeholder="Khoản tiền này dùng để làm gì?">${esc(t.note)}</textarea></label><div id="tx-warning" class="full"></div></div>${type==='loan'?'<p class="inline-info">Nhận tiền vay tăng cả tiền vay còn lại và dư nợ. Khoản này không được tính là thu nhập.</p>':''}${type==='repay'?`<p class="inline-info">Dư nợ hiện tại: <strong>${fmt(b.debt)}</strong>. Trả gốc làm giảm dư nợ; lãi / phí được tính vào chi tiêu tháng. Khi dư nợ giảm thấp hơn tiền vay còn lại, phần tiền không còn bị ràng buộc sẽ chuyển sang quỹ chi tiêu.</p>`:''}<p class="form-error" role="alert"></p><div class="form-actions"><button type="button" id="cancel-tx">Hủy</button><button class="primary" type="submit">${existing?'Lưu thay đổi':'Lưu giao dịch'}</button></div></form>`);
    const form=$('#tx-form');
    function warning(){const a=form.elements.account.value;$('#account-balance').textContent='Số dư hiện tại: '+fmt(b[a]);let content='';if(type==='expense'&&a==='borrow')content='Bạn đang tiêu tiền vay. Không nên dùng khoản này cho chi tiêu thông thường: tiền trong tay giảm nhưng dư nợ vẫn giữ nguyên.';if((type==='expense'||type==='repay')&&a==='save')content='Bạn đang sử dụng tiền tiết kiệm. Giao dịch này sẽ làm giảm quỹ dự phòng và tiến độ mục tiêu.';$('#tx-warning').innerHTML=content?`<label class="check-row"><input type="checkbox" name="ack" required><span>${content}<br><strong>Tôi hiểu và vẫn muốn ghi nhận.</strong></span></label>`:'';if(type==='transfer')form.elements.to.value=a==='spend'?'save':'spend';}
    warning();form.elements.account.onchange=warning;
    form.elements.amount.oninput=()=>{try{$('#amount-preview').textContent=fmt(C.moneyInput(form.elements.amount.value));}catch{$('#amount-preview').textContent='Nhập số nguyên VNĐ, có thể dùng dấu chấm phân cách.';}};
    $$('[data-type]').forEach(btn=>btn.onclick=()=>{const d=new FormData(form);let amt=0;try{amt=C.moneyInput(d.get('amount')||'0');}catch{}transactionForm(btn.dataset.type,null,{...t,amount:amt,account:d.get('account'),date:d.get('date')||C.today(),note:d.get('note')});});
    $('#cancel-tx').onclick=()=>modal.close();
    form.onsubmit=async e=>{
      e.preventDefault();e.submitter.disabled=true;
      try{
        const f=new FormData(form),a=f.get('account');
        if(((type==='expense'&&(a==='borrow'||a==='save'))||(type==='repay'&&a==='save'))&&!f.get('ack'))throw new Error('Hãy đọc và xác nhận cảnh báo trước khi lưu.');
        const tx={id:existing?.id||('tx_'+(crypto.randomUUID?crypto.randomUUID():Date.now()+'_'+Math.random().toString(36).slice(2))),date:f.get('date'),type,amount:C.moneyInput(f.get('amount'),true),interest:type==='repay'?C.moneyInput(f.get('interest')):0,account:a,to:type==='transfer'?f.get('to'):'',category:type==='expense'?f.get('category'):type==='repay'?'Trả nợ':C.labels[type],note:f.get('note').trim()};
        let n;if(existing){n=JSON.parse(JSON.stringify(state));n.transactions[n.transactions.findIndex(x=>x.id===existing.id)]=tx;C.validate(n);}else n=C.add(state,tx);
        await commit(n);modal.close();notify(existing?'Đã cập nhật giao dịch.':'Đã lưu giao dịch.');
      }catch(err){errorIn(form,err);}finally{e.submitter.disabled=false;}
    };
  }
  function budgetBlock(stats){const limit=state.settings.budget,spent=stats.expense,pct=limit?Math.min(100,Math.round(spent/limit*100)):0;return `<div class="budget-track ${limit&&spent>limit?'over':''}"><span style="width:${pct}%"></span></div><div class="budget-line"><span>${limit?'Ngân sách tháng: '+fmt(limit):'Chưa đặt ngân sách tháng'}</span><span>${limit?(spent>limit?'Vượt '+fmt(spent-limit):'Còn '+fmt(limit-spent)):'Đặt trong Kế hoạch'}</span></div>`;}
  function emptyTransactions(){return '<div class="empty"><div class="empty-icon" aria-hidden="true">⇄</div><h3>Chưa có giao dịch</h3><p>Ghi lại một khoản thu hoặc chi để bắt đầu nhìn rõ dòng tiền của bạn.</p><button data-action="add">+ Ghi giao dịch</button></div>';}
  function txRows(ts,full=false){return ts.map(t=>`<tr><td><div class="tx-main"><span class="tx-icon ${t.type}" aria-hidden="true">${{income:'+',expense:'−',transfer:'⇄',loan:'+',repay:'−'}[t.type]}</span><div><div class="tx-title">${esc(t.note||t.category)}</div><div class="tx-meta">${esc(C.labels[t.type])} · ${day(t.date)}</div></div></div></td><td class="amount ${t.type==='repay'?'expense':t.type}">${{income:'+',expense:'−',transfer:'⇄ ',loan:'+',repay:'−'}[t.type]}${fmt(t.amount+t.interest)}${t.interest?`<div class="tx-meta">Lãi / phí: ${fmt(t.interest)}</div>`:''}</td><td><span class="tx-meta">${esc(C.names[t.account])}${t.type==='transfer'?'<br>→ '+esc(C.names[t.to]):''}</span></td>${full?`<td><button class="quiet" data-edit="${t.id}" aria-label="Sửa ${esc(t.note||t.category)}">Sửa</button><button class="quiet danger" data-delete="${t.id}" aria-label="Xóa ${esc(t.note||t.category)}">Xóa</button></td>`:''}</tr>`).join('');}
  function table(ts,full=false){return ts.length?`<div class="table-wrap"><table><thead><tr><th>Giao dịch</th><th class="amount">Số tiền</th><th>Quỹ tiền</th>${full?'<th><span class="sr-only">Thao tác</span></th>':''}</tr></thead><tbody>${txRows(ts,full)}</tbody></table></div>`:emptyTransactions();}
  const sorted=ts=>ts.map((t,i)=>({t,i})).sort((a,b)=>b.t.date.localeCompare(a.t.date)||b.i-a.i).map(x=>x.t);
  function overview(){
    const b=current(),s=C.stats(state,selectedMonth),recent=sorted(state.transactions.filter(t=>t.date.startsWith(selectedMonth))).slice(0,5),cats=Object.entries(s.categories).sort((a,b)=>b[1]-a[1]);
    return `<div class="hero-grid"><article class="spend-card"><span class="small-label">TIỀN RIÊNG CÓ THỂ CHI</span><div class="spend-value">${fmt(b.spend)}</div><p>Đã tách riêng tiết kiệm và tiền vay.</p><div class="spend-bottom"><span>Tổng tiền đang giữ</span><strong>${fmt(b.total)}</strong></div></article><article class="panel"><div class="panel-heading"><h2>Thu & chi trong tháng</h2><span class="pill">${esc(selectedMonth.split('-').reverse().join('/'))}</span></div><div class="cashflow"><div><div class="label">↙ Tiền thêm vào</div><div class="value income">+${fmt(s.income)}</div><span class="fine muted">Không gồm tiền vay</span></div><div><div class="label">↗ Đã chi tiêu</div><div class="value expense">−${fmt(s.expense)}</div><span class="fine muted">Gồm lãi / phí vay</span></div></div>${budgetBlock(s)}</article></div><div class="balance-grid"><article class="panel balance-card"><div class="balance-top"><span class="label">Tiền tiết kiệm</span><span class="mini-icon" aria-hidden="true">◎</span></div><div class="value">${fmt(b.save)}</div><p>Giữ cho những điều quan trọng</p></article><article class="panel balance-card"><div class="balance-top"><span class="label">Tiền vay còn lại</span><span class="mini-icon amber" aria-hidden="true">!</span></div><div class="value loan">${fmt(b.borrow)}</div><p>Cần cân nhắc trước khi sử dụng</p></article><article class="panel balance-card"><div class="balance-top"><span class="label">Dư nợ gốc phải trả</span><span class="mini-icon red" aria-hidden="true">↗</span></div><div class="value expense">${fmt(b.debt)}</div><p>Tiêu tiền vay không làm giảm nợ</p></article></div>${b.borrow?`<div class="notice warning"><p><strong>${fmt(b.borrow)} đang là tiền vay.</strong> Khoản này được giữ riêng và không nằm trong số tiền riêng có thể chi.</p><button data-action="repay">Ghi trả nợ</button></div>`:''}<div class="lower-grid"><article class="panel"><div class="panel-heading"><h2>Giao dịch gần đây</h2><button class="quiet" data-action="transactions">Xem tất cả</button></div>${table(recent)}</article><article class="panel"><div class="panel-heading"><h2>Tiền đã đi đâu?</h2><span class="pill">${cats.length} danh mục</span></div>${cats.length?cats.map(([k,v])=>`<div class="category-row"><div><span>${esc(k)}</span><strong>${fmt(v)}</strong></div><div class="budget-track"><span style="width:${Math.round(v/s.expense*100)}%"></span></div></div>`).join(''):'<div class="empty"><div class="empty-icon" aria-hidden="true">◎</div><p>Các danh mục chi tiêu sẽ hiện ở đây khi bạn ghi khoản chi đầu tiên.</p></div>'}<div class="net-line"><span>Tài sản ròng trong sổ<br><span class="fine muted">Tổng tiền giữ − dư nợ</span></span><strong class="${b.net<0?'expense':''}">${fmt(b.net)}</strong></div></article></div><p class="fine muted spaced">Số dư quỹ là số hiện tại của toàn bộ sổ. Bộ lọc tháng chỉ áp dụng cho thu, chi và danh sách giao dịch. Tài sản ròng ở đây chỉ tính các khoản đã nhập vào app.</p>`;
  }
  function filtered(){return sorted(state.transactions.filter(t=>t.date.startsWith(selectedMonth)&&(!filter.type||t.type===filter.type)&&(!filter.account||t.account===filter.account||t.to===filter.account)&&(!filter.q||[t.note,t.category,C.labels[t.type]].join(' ').toLocaleLowerCase('vi').includes(filter.q.toLocaleLowerCase('vi')))));}
  function transactionView(){const ts=filtered(),s=C.stats(state,selectedMonth),pages=Math.max(1,Math.ceil(ts.length/30));pageIndex=Math.min(pageIndex,pages-1);return `<div class="totals-strip"><span class="muted">Thêm tiền<strong class="income">+${fmt(s.income)}</strong></span><span class="muted">Chi tiêu & lãi / phí<strong class="expense">−${fmt(s.expense)}</strong></span><span class="muted">Gốc nợ đã trả<strong>${fmt(s.principal)}</strong></span><span class="muted">Tiền vay nhận thêm<strong class="loan">${fmt(s.loan)}</strong></span></div><div class="panel"><div class="filters"><input type="search" id="search" placeholder="Tìm ghi chú, danh mục…" aria-label="Tìm giao dịch" value="${esc(filter.q)}"><select id="type-filter" aria-label="Lọc loại giao dịch">${options([['','Mọi giao dịch'],...C.types.map(k=>[k,C.labels[k]])],filter.type)}</select><select id="account-filter" aria-label="Lọc quỹ tiền">${options([['','Mọi quỹ tiền'],...C.accounts.map(k=>[k,C.names[k]])],filter.account)}</select><button id="csv-button">Xuất CSV</button></div><p class="fine muted">${ts.length} giao dịch phù hợp · Thống kê phía trên tính toàn bộ tháng.</p><div id="transaction-table">${table(ts.slice(pageIndex*30,pageIndex*30+30),true)}</div><div class="pagination"><span>Trang ${pageIndex+1} / ${pages}</span><div><button id="prev-page" ${pageIndex===0?'disabled':''}>Trước</button> <button id="next-page" ${pageIndex===pages-1?'disabled':''}>Sau</button></div></div></div>`;}
  function planning(){const b=current(),s=C.stats(state,selectedMonth),p=state.settings,progress=p.goal?Math.min(100,Math.round(b.save/p.goal*100)):0;return `<div class="two-col"><article class="panel"><div class="panel-heading"><h2>Ngân sách tháng</h2><span class="pill">${esc(selectedMonth)}</span></div><div class="big-stat">${fmt(s.expense)}</div><p class="fine muted">Chi tiêu và lãi / phí đã ghi trong tháng.</p>${budgetBlock(s)}<form id="budget-form" class="spaced">${moneyField('Giới hạn chi tiêu mỗi tháng','budget',p.budget,'Áp dụng chung cho các tháng. Nhập 0 để không đặt giới hạn.')}<p class="form-error" role="alert"></p><div class="form-actions"><button class="primary">Lưu ngân sách</button></div></form><p class="fine muted">Chuyển quỹ và trả gốc nợ không tính vào chi tiêu. Hãy dành riêng tiền trả nợ khi lên kế hoạch.</p></article><article class="panel"><div class="panel-heading"><h2>Mục tiêu tiết kiệm</h2><span class="pill">${progress}%</span></div><div class="big-stat">${fmt(b.save)}</div><p class="fine muted">${p.goal?'Còn '+fmt(Math.max(0,p.goal-b.save))+' để đạt mục tiêu.':'Đặt mục tiêu đầu tiên của bạn.'}</p><div class="budget-track"><span style="width:${progress}%"></span></div><form id="goal-form" class="spaced"><label class="field">Tên mục tiêu<input name="goalName" maxlength="80" value="${esc(p.goalName)}" required></label><div class="spaced">${moneyField('Số tiền mục tiêu','goal',p.goal,'Theo dõi theo tổng quỹ tiết kiệm hiện tại.')}</div><p class="form-error" role="alert"></p><div class="form-actions"><button type="button" data-action="transfer">Chuyển vào tiết kiệm</button><button class="primary">Lưu mục tiêu</button></div></form></article></div><article class="panel wide-panel"><div class="panel-heading"><h2>Khoản trả nợ sắp tới</h2><span class="pill">Nhắc khi mở app</span></div><form id="due-form"><div class="form-grid"><label class="field">Ngày cần trả<input type="date" name="dueDate" value="${esc(p.dueDate)}" min="1900-01-01" max="2199-12-31"><span class="hint">Để trống ngày và nhập 0 để tắt nhắc.</span></label>${moneyField('Số tiền dự kiến phải trả','dueAmount',p.dueAmount,'Nhập theo lịch trả nợ của bạn; có thể gồm cả gốc và lãi.')}</div><p class="fine muted spaced">Đây là nhắc việc bạn tự đặt, không tự trừ tiền hoặc tự tính lãi. Sau khi trả xong, hãy ghi giao dịch và cập nhật kỳ tiếp theo. Bản này theo dõi dư nợ tổng, chưa chia theo từng chủ nợ.</p><p class="form-error" role="alert"></p><div class="form-actions"><button type="button" data-action="repay">Ghi trả nợ</button><button class="primary">Lưu lịch nhắc</button></div></form></article>`;}
  function backupView(){let last='Chưa xuất bản sao lưu';try{const t=localStorage.getItem(BACKUP);if(t)last='Lần tạo tệp gần nhất: '+new Date(t).toLocaleString('vi-VN');}catch{}return `<div class="notice"><p><strong>Tự lưu không thay thế bản sao lưu.</strong> Xóa dữ liệu trình duyệt, đổi máy hoặc đổi địa chỉ website có thể khiến bạn không thấy sổ hiện tại. Hãy xuất JSON định kỳ.</p></div><div class="backup-grid"><article class="panel backup-card"><h2>Xuất bản sao lưu</h2><p>Giữ đầy đủ số dư ban đầu, giao dịch và kế hoạch trong một tệp JSON. Dùng tệp này để chuyển máy hoặc khôi phục.</p><p class="fine">${esc(last)}</p><button class="primary" id="export-button" ${storageProblem?'disabled':''}>Tải bản sao lưu JSON</button></article><article class="panel backup-card"><h2>Nhập lại dữ liệu</h2><p>Chọn tệp JSON của Ví Rõ. Bạn sẽ được xem tổng tiền trước khi xác nhận thay thế sổ hiện tại. Không gộp hai sổ để tránh ghi trùng giao dịch.</p><input class="file-input" type="file" id="import-file" accept=".json,application/json" aria-label="Chọn tệp sao lưu JSON"><p id="import-error" class="form-error" role="alert"></p></article><article class="panel backup-card"><h2>Phục hồi thay đổi gần nhất</h2><p>App giữ thêm một bản trước lần lưu thành công gần nhất trên trình duyệt. Có thể dùng để quay lại sau khi sửa nhầm hoặc nhập nhầm tệp.</p><button id="restore-button">Xem bản phục hồi</button></article><article class="panel backup-card"><h2>Số dư ban đầu</h2><p>Điều chỉnh tiền riêng, tiết kiệm, tiền vay và dư nợ lúc bắt đầu dùng sổ. App sẽ kiểm tra lại toàn bộ lịch sử.</p><button data-action="setup">${state.initialized?'Điều chỉnh số dư':'Nhập số dư ban đầu'}</button></article></div><article class="panel wide-panel"><h2>Dữ liệu của bạn được lưu ở đâu?</h2><p class="fine muted spaced">Trên trình duyệt này, tại địa chỉ website này. App không có máy chủ nhận giao dịch, không có quảng cáo hoặc công cụ theo dõi. Không có đồng bộ tự động giữa các máy, tài khoản đăng nhập hay mã hóa bản sao lưu. Người dùng chung hồ sơ trình duyệt này có thể xem sổ.</p><p class="fine muted">Chỉ đưa mã ứng dụng lên GitHub. Giữ các tệp JSON / CSV tài chính ở nơi riêng của bạn. Các website cùng tên miền gốc có thể chia sẻ vùng lưu trữ trình duyệt; chỉ đặt app cùng các website bạn tin cậy.</p><div class="flex-between"><button id="raw-button">Tải dữ liệu gốc để cứu hộ</button><button class="danger" id="reset-button">Xóa sổ trên trình duyệt</button></div></article>`;}
  function render(){
    cache=null;$('#page-title').textContent=titles[page];$('#breadcrumb-view').textContent=titles[page];$('#page-eyebrow').textContent={overview:'NHÌN RÕ DÒNG TIỀN',transactions:'MỖI KHOẢN TIỀN, MỘT DẤU VẾT',planning:'CHỦ ĐỘNG CHO NGÀY MAI',backup:'GIỮ SỔ TIỀN TRONG TAY BẠN'}[page];
    $('#month').value=selectedMonth;$('.month-label').hidden=!['overview','transactions'].includes(page);
    $$('nav [data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===page);if(b.dataset.view===page)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});
    $('#save-status').textContent=storageProblem?'Cần phục hồi dữ liệu':state.updatedAt?'Đã lưu lúc '+new Date(state.updatedAt).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'}):'Tự lưu trên thiết bị';
    let notice='';
    if(storageProblem)notice=`<div class="notice error"><p>${esc(storageProblem)}</p><button data-action="backup">Mở sao lưu</button></div>`;
    else if(!state.initialized)notice='<div class="notice"><p><strong>Chào bạn, bắt đầu bằng số tiền hiện có nhé.</strong><br>Nhập riêng tiền chi tiêu, tiết kiệm và tiền vay.</p><button class="primary" data-action="setup">Nhập số dư ban đầu</button></div>';
    const d=state.settings;
    if(!storageProblem&&d.dueDate&&d.dueAmount&&current().debt>0){const days=Math.ceil((new Date(d.dueDate+'T12:00:00')-new Date(C.today()+'T12:00:00'))/86400000);if(days<=7)notice+=`<div class="notice warning"><p><strong>${days<0?'Ngày nhắc trả nợ đã qua '+(-days)+' ngày':days===0?'Hôm nay là ngày nhắc trả nợ':'Còn '+days+' ngày đến lịch nhắc trả nợ'}</strong> · ${day(d.dueDate)} · ${fmt(d.dueAmount)}. Nếu đã trả, hãy cập nhật lịch nhắc.</p><button data-action="repay">Ghi trả nợ</button></div>`;}
    try{const last=localStorage.getItem(BACKUP);if(state.transactions.length&&(!last||Date.now()-Date.parse(last)>7*86400000)&&page!=='backup')notice+='<div class="notice"><p>Bạn chưa tạo tệp sao lưu trong 7 ngày qua. Giữ một bản để phòng mất dữ liệu trình duyệt.</p><button data-action="export">Sao lưu ngay</button></div>';}catch{}
    $('#global-notice').innerHTML=notice;
    $('#view').innerHTML=({overview,transactions:transactionView,planning,backup:backupView})[page]();
    bind();
  }
  function navigate(next){page=titles[next]?next:'overview';pageIndex=0;render();}
  function bind(){
    $$('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='setup')setup();else if(a==='export')exportJSON();else if(a==='add')transactionForm();else if(['repay','transfer'].includes(a))transactionForm(a);else navigate(a);});
    $$('[data-edit]').forEach(b=>b.onclick=()=>{const t=state.transactions.find(x=>x.id===b.dataset.edit);transactionForm(t.type,t);});
    $$('[data-delete]').forEach(b=>b.onclick=()=>{const t=state.transactions.find(x=>x.id===b.dataset.delete);confirmAction('Xóa giao dịch?',`<p>${esc(t.note||t.category)} · <strong>${fmt(t.amount+t.interest)}</strong> · ${day(t.date)}</p><p class="fine muted">Số dư sẽ được tính lại. Nếu các giao dịch sau đó phụ thuộc vào khoản này, app sẽ chặn thao tác gây số dư âm.</p>`,async()=>{await commit(C.remove(state,t.id));notify('Đã xóa giao dịch. Có thể phục hồi lần lưu trước trong Dữ liệu & sao lưu.');},'Xóa giao dịch');});
    if(page==='transactions'){
      $('#search').oninput=e=>{const pos=e.target.selectionStart;filter.q=e.target.value;pageIndex=0;render();$('#search').focus();$('#search').setSelectionRange(pos,pos);};
      $('#type-filter').onchange=e=>{filter.type=e.target.value;pageIndex=0;render();};$('#account-filter').onchange=e=>{filter.account=e.target.value;pageIndex=0;render();};
      $('#prev-page').onclick=()=>{pageIndex--;render();};$('#next-page').onclick=()=>{pageIndex++;render();};$('#csv-button').onclick=exportCSV;
    }
    if(page==='planning'){
      [['budget-form',['budget']],['goal-form',['goalName','goal']],['due-form',['dueDate','dueAmount']]].forEach(([id,keys])=>{$('#'+id).onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{const f=new FormData(e.target),n=JSON.parse(JSON.stringify(state));for(const k of keys)n.settings[k]=['goalName','dueDate'].includes(k)?f.get(k):C.moneyInput(f.get(k));if(id==='due-form'&&Boolean(n.settings.dueDate)!==Boolean(n.settings.dueAmount))throw new Error('Nhập đủ ngày và số tiền; hoặc xóa ngày và đặt số tiền là 0 để tắt.');await commit(n);notify('Đã lưu kế hoạch.');}catch(err){errorIn(e.target,err);e.submitter.disabled=false;}};});
    }
    if(page==='backup'){
      $('#export-button').onclick=()=>exportJSON();$('#import-file').onchange=importFile;
      $('#restore-button').onclick=()=>{try{const raw=localStorage.getItem(PREV);if(!raw)throw new Error('Chưa có bản phục hồi. Bản này xuất hiện sau khi bạn lưu thay đổi lần tiếp theo.');const n=C.validate(JSON.parse(raw));previewImport(n,true);}catch(e){notify(e.message);}};
      $('#raw-button').onclick=()=>{try{const raw=localStorage.getItem(KEY);if(!raw){notify('Chưa có dữ liệu gốc.');return;}download(raw,`ViRo-rescue-${C.today()}.json`);notify('Đã tạo tệp cứu hộ dữ liệu gốc. Tệp này dành cho kiểm tra kỹ thuật.');}catch(e){notify(e.message);}};
      $('#reset-button').onclick=()=>confirmAction('Xóa toàn bộ sổ trên trình duyệt?',`<p>Toàn bộ giao dịch và kế hoạch hiện tại sẽ bị xóa. Hãy tải bản sao lưu trước khi tiếp tục.</p><label class="check-row"><input id="reset-ack" type="checkbox"><span>Tôi đã giữ bản sao lưu cần thiết và muốn xóa sổ.</span></label>`,async()=>{if(!$('#reset-ack').checked)throw new Error('Hãy xác nhận đã giữ bản sao lưu.');await commit(C.empty(),{recovery:true});notify('Đã xóa sổ. Bản phục hồi trước đó vẫn được giữ.');},'Xóa sổ');
    }
  }
  function previewImport(n,restore=false){const b=C.ledger(n);confirmAction(restore?'Phục hồi bản trước?':'Thay thế sổ bằng bản sao lưu?',`<p><strong>${n.transactions.length} giao dịch</strong> · Tổng tiền: <strong>${fmt(b.total)}</strong></p><p class="fine muted">Tiền riêng: ${fmt(b.spend)}<br>Tiết kiệm: ${fmt(b.save)}<br>Tiền vay còn lại: ${fmt(b.borrow)}<br>Dư nợ: ${fmt(b.debt)}</p><div class="notice warning"><p>Thao tác này thay thế toàn bộ sổ hiện tại. Bản hiện tại hợp lệ sẽ được giữ trong mục Phục hồi thay đổi gần nhất.</p></div>`,async()=>{await commit(n,{recovery:true});notify('Đã phục hồi dữ liệu.');},restore?'Phục hồi':'Thay thế dữ liệu');}
  async function importFile(e){const f=e.target.files[0];if(!f)return;try{if(f.size>8000000)throw new Error('Tệp vượt giới hạn 8 MB.');previewImport(C.parseBackup(await f.text()));}catch(err){$('#import-error').textContent=err.message;}finally{e.target.value='';}}
  function exportCSV(){
    const cell=v=>{let s=String(v??'');if(/^[=+\-@\t\r\n]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};
    const rows=[['Ngày','Loại','Quỹ nguồn','Quỹ đích','Số tiền VNĐ','Lãi phí VNĐ','Danh mục','Ghi chú'],...filtered().map(t=>[t.date,C.labels[t.type],C.names[t.account],C.names[t.to]||'',t.amount,t.interest,t.category,t.note])];
    download('\uFEFF'+rows.map(r=>r.map(cell).join(',')).join('\r\n'),`ViRo-giao-dich-${selectedMonth}.csv`,'text/csv;charset=utf-8');notify('Đã xuất các giao dịch theo bộ lọc. CSV để đọc trong Excel; JSON để phục hồi.');
  }
  function guide(){showModal('Dùng Ví Rõ trong 3 bước','Một sổ tiền đơn giản, tách rõ tiền của bạn và tiền vay.',`<ol class="steps"><li><strong>Nhập số dư ban đầu.</strong> Tách tiền riêng, tiết kiệm, tiền vay còn lại và dư nợ gốc.</li><li><strong>Ghi giao dịch mỗi ngày.</strong> Thêm tiền màu xanh, chi tiền màu đỏ, chuyển quỹ màu xanh lam, nhận tiền vay màu vàng.</li><li><strong>Xuất JSON định kỳ.</strong> Khi đổi máy, mở cùng ứng dụng rồi nhập bản sao lưu.</li></ol><p class="inline-info">Chuyển tiền giữa hai quỹ không làm tăng thu nhập hay chi tiêu. Nhận tiền vay không phải thu nhập. Trả gốc làm giảm nợ; trả lãi / phí được tính là chi tiêu.</p><p class="fine muted spaced">Ngân sách do bạn tự đặt. App ghi chép và nhắc việc khi mở; không kết nối ngân hàng, không tự tính lãi, không gửi thông báo khi đóng app.</p>`);}
  $('#add-button').onclick=()=>transactionForm();$('#guide-button').onclick=guide;
  $$('nav [data-view]').forEach(b=>b.onclick=()=>navigate(b.dataset.view));$('.brand').onclick=e=>{e.preventDefault();navigate('overview');};
  $('#month').value=selectedMonth;$('#month').onchange=e=>{if(/^\d{4}-\d{2}$/.test(e.target.value)){selectedMonth=e.target.value;pageIndex=0;render();}};
  window.addEventListener('storage',e=>{if(e.key===KEY&&e.newValue!==baseRaw){notify('Sổ đã thay đổi ở tab khác. Tải lại trang để tiếp tục.');$('#save-status').textContent='Tab khác đã thay đổi dữ liệu · hãy tải lại';}});
  load();render();
  // Optional browser agent integration: read-only, uses the same verified ledger.
  try{if(document.modelContext?.registerTool)Promise.resolve(document.modelContext.registerTool({name:'read_viro_summary',title:'Đọc tổng quan Ví Rõ',description:'Read current wallet balances and the selected month summary without changing data.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected an empty object.');if(storageProblem)throw new Error('Dữ liệu cần phục hồi.');return {currency:'VND',balances:current(),month:selectedMonth,monthly:C.stats(state,selectedMonth)};}})).catch(()=>{});}catch{}
})();
